server:
  port: 8080

spring:
  aplication:
    name: microservices
  jpa:
    show-sql: false
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL8Diailect
      jmx:
        enable: false
      datasource:
        url: jdbc:mysql://localhost:3306/dbmicroservices?allowPublickeyRetrieval=true&sslMode=Disable
        username: root
        password: 102030


