# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3030:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 102030
    volumes:
        - microservices:/home/projects/mysql
volumes:
  microservices: